import pygame

SCREEN_WIDTH: int = 880
SCREEN_HEIGHT: int = 550
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

FLOOR_WIDTH = 100
FLOOR_HEIGHT = 40

ELEVATOR_WIDTH = 20
ELEVATOR_HEIGHT = FLOOR_HEIGHT

BUTTON_WIDTH = FLOOR_WIDTH / 5
BUTTON_HEIGHT = FLOOR_HEIGHT - 8

LINE_WIDTH = FLOOR_WIDTH
LINE_HEIGHT = 7

NUMBER_OF_BUILDING = 1
NUMBER_OF_FLOORS = 10
NUMBER_OF_ELEVATORS = 3

BUILDING_SPACING = 100

FPS = 60

# BACKGROUND_IMAGE = pygame.image.load()
# BACKGROUND_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT
# BACKGROUND_SCALE = pygame.transform.scale(BACKGROUND_IMAGE, BACKGROUND_SIZE)

FLOOR_IMAGE = pygame.image.load("audio_and_images/floor.png")
FLOOR_SIZE = FLOOR_WIDTH, FLOOR_HEIGHT
FLOOR_SCALE = pygame.transform.scale(FLOOR_IMAGE, FLOOR_SIZE)

ELEVATOR_IMAGE = pygame.image.load("audio_and_images/elv.png")
ELEVATOR_SIZE = ELEVATOR_WIDTH, ELEVATOR_HEIGHT
ELEVATOR_SCALE = pygame.transform.scale(ELEVATOR_IMAGE, ELEVATOR_SIZE)
