import pygame

SCREEN_WIDTH: int = 1200
SCREEN_HEIGHT: int = 700
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Elevator Challenge")

FLOOR_WIDTH = 100
FLOOR_HEIGHT = 40

ELEVATOR_WIDTH = 20
ELEVATOR_HEIGHT = FLOOR_HEIGHT

BUTTON_WIDTH = FLOOR_WIDTH / 5
BUTTON_HEIGHT = FLOOR_HEIGHT / 2

LINE_WIDTH = FLOOR_WIDTH
LINE_HEIGHT = 7

NUMBER_OF_BUILDING = 6
NUMBER_OF_FLOORS = 20
NUMBER_OF_ELEVATORS = 5

BUILDING_SPACING = 100

TIMER_FONT_SIZE = 24

MAX_BUILDING_SCREEN = SCREEN_WIDTH // (TIMER_FONT_SIZE + 30 + FLOOR_WIDTH + (ELEVATOR_WIDTH * NUMBER_OF_ELEVATORS) + 5)
MAX_FLOORS_SCREEN = (SCREEN_HEIGHT - 10) // (FLOOR_HEIGHT)

MAX_NUMBER_OF_BUILDING = min(NUMBER_OF_BUILDING, MAX_BUILDING_SCREEN)
MAX_NUMBER_OF_FLOOR = min(NUMBER_OF_FLOORS, MAX_FLOORS_SCREEN)

FPS = 60
SPEED = 1

FLOOR_IMAGE = pygame.image.load("audio_and_images/floor.png")
FLOOR_SIZE = FLOOR_WIDTH, FLOOR_HEIGHT
FLOOR_SCALE = pygame.transform.scale(FLOOR_IMAGE, FLOOR_SIZE)

ELEVATOR_IMAGE = pygame.image.load("audio_and_images/elv.png")
ELEVATOR_SIZE = ELEVATOR_WIDTH, ELEVATOR_HEIGHT
ELEVATOR_SCALE = pygame.transform.scale(ELEVATOR_IMAGE, ELEVATOR_SIZE)
